apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: openefsafoodexwebcomponentbackend 
spec:
  progressDeadlineSeconds: 900
  replicas: 1
  template:
    metadata:
      labels:
        app: openefsafoodexwebcomponentbackend 
    spec:
      containers:
        - name: openefsafoodexwebcomponentbackend 
          image: efsadsreg.azurecr.io/openefsafoodexwebcomponentbackend
          volumeMounts:
           - name: workdir
             mountPath: "/work-dir"
          ports:
          - containerPort: 5000
          resources:
            requests:
              memory: "32Gi"
              cpu: "250m"
            limits:
              memory: "40Gi"
              cpu: "500m"
      initContainers:
      - name: download-models
        image: curlimages/curl
        command:
        - curl
        - https://efsapublicmodels.blob.core.windows.net/efsapublicmodels/FOODEX/foodex2PreditionDeployed.zip
        - "-o"
        - "/work-dir/foodex2PreditionDeployed.zip"  
        volumeMounts:
           - name: workdir
             mountPath: "/work-dir"
      - name: unzip-models
        image: curlimages/curl
        command: ["unzip", "/work-dir/foodex2PreditionDeployed.zip", "-d", "/work-dir"]
        volumeMounts:
           - name: workdir
             mountPath: "/work-dir"
      volumes:
        - name: workdir
          emptyDir: {}       
