apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: openefsafoodexwebcomponentbackend 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openefsafoodexwebcomponentbackend 
    spec:
      containers:
        - name: openefsafoodexwebcomponentbackend 
          image: efsadsreg.azurecr.io/openefsafoodexwebcomponentbackend:v4
          ports:
          - containerPort: 5000
          resources:
            requests:
              memory: "32Gi"
              cpu: "250m"
            limits:
              memory: "40Gi"
              cpu: "500m"
            
