apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: openefsafoodexwebcomponentbackend 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openefsafoodexwebcomponentbackend 
    spec:
      containers:
        - name: openefsafoodexwebcomponentbackend 
          image: efsadsreg.azurecr.io/openefsafoodexwebcomponentbackend
          ports:
          - containerPort: 5000